groqcloud:
  api:
    key: Bearer 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
    endpoint: https://api.groq.com/openai/v1/chat/completions

spring:
  data:
    mongodb:
      uri: mongodb+srv://elserlazaro:MroUxZM8CbXLMPKk@cluster0.brvyv.mongodb.net/MongoAtlaCompons?retryWrites=true&w=majority

springdoc:
  swagger-ui:
    path: /swagger-ui.html

server:
  port: 8081
