apiVersion: v1
kind: Secret
metadata:
  name: elsermanuel-secret
  namespace: elsermanuel
type: Opaque
stringData:
  GROQCLOUD_API_KEY: "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"
  GROQCLOUD_ENDPOINT: "https://api.groq.com/openai/v1/chat/completions"
  MONGODB_URI: "mongodb+srv://elserlazaro:MroUxZM8CbXLMPKk@cluster0.brvyv.mongodb.net/MongoAtlaCompons?retryWrites=true&w=majority"