apiVersion: v1
kind: Service
metadata:
  name: elsermanuel-service
  namespace: elsermanuel
spec:
  selector:
    app: elsermanuel
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8081
      nodePort: 30100
  type: NodePort