name: SonarCloud
on:
  push:
    branches:
      - main
      - develop  # Se ejecutará en las ramas main y develop
  pull_request:
    branches:
      - main
      - develop  # Se ejecutará en pull requests hacia las ramas main y develop
    types: [opened, synchronize, reopened]
jobs:
  build:
    name: Build and analyze
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Clonación completa para una mejor relevancia del análisis
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'  # Asegúrate de usar Java 21
          distribution: 'zulu'  # O considera usar otra distribución como 'temurin'
      - name: Cache SonarCloud packages
        uses: actions/cache@v4
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar
          restore-keys: ${{ runner.os }}-sonar
      - name: Cache Maven packages
        uses: actions/cache@v4
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2
      - name: Build and analyze
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Necesario para obtener información del PR
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}  # Token de SonarCloud
        run: mvn -B verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar -Dsonar.projectKey=ElserManuel_AS222S5_T05_be
